# FICO's Conda builds are available at:
# https://anaconda.org/fico-xpress/xpress/files
#
# git-tree-sha1 and sha256 can be updated as follows:
# ```julia
# arch = "osx-arm64"
# filename = "xpress-9.3.0-py310h2690037_0.tar.bz2"
# run(`wget https://anaconda.org/fico-xpress/xpress/9.3.0/download/$arch/$filename`)
# using Tar, Inflate, SHA
# println("sha256: ", bytes2hex(open(sha256, filename)))
# println("git-tree-sha1: ", Tar.tree_hash(`gzcat $filename`))
# ```

[[Xpress]]
git-tree-sha1 = "401f814491e641f375c84ea3bb3051a38bc2fd55"
os = "linux"
arch = "x86_64"

    [[Xpress.download]]
    url = "https://anaconda.org/fico-xpress/xpress/9.3.0/download/linux-64/xpress-9.3.0-py310ha14b774_0.tar.bz2"
    sha256 = "48fed11b039d260f0ed90bfa1e41f23561f76c71796dc926a000d17151b9f801"

[[Xpress]]
git-tree-sha1 = "75e700f837add542a01f8b00fa20efb25a16c4f7"
os = "macos"
arch = "x86_64"

    [[Xpress.download]]
    url = "https://anaconda.org/fico-xpress/xpress/9.3.0/download/osx-64/xpress-9.3.0-py310h9b76c6a_0.tar.bz2"
    sha256 = "e8734d813d3872fe6a6c907ea4767e4b93af55f495e33b8726eb338392a16dc3"

[[Xpress]]
git-tree-sha1 = "399838f7f70550762eb5f2d603e5e184ba564794"
os = "macos"
arch = "aarch64"

    [[Xpress.download]]
    url = "https://anaconda.org/fico-xpress/xpress/9.3.0/download/osx-arm64/xpress-9.3.0-py310h2690037_0.tar.bz2"
    sha256 = "bfd91e3191a12549924e00dcc2aed05518202a756a0ed083e535c2e0d2961e19"

[[Xpress]]
git-tree-sha1 = "554491bde6b59b4c1a1994ce39ba46cb9342510b"
os = "windows"
arch = "x86_64"

    [[Xpress.download]]
    url = "https://anaconda.org/fico-xpress/xpress/9.3.0/download/win-64/xpress-9.3.0-py310hadc54f4_0.tar.bz2"
    sha256 = "d44f7db6de16461c428c628217e56cdc51a40a6d662d7db66b7d8a4a414df68f"
